### PR TITLE
Make Label localizable

### PR DESCRIPTION
**Pull request by vavanv**
Change SetContextmethod  in State class to allow set label from Display attribute which is localized.

### CODE REVIEW

**Comment by thelarz** [comment]
Can you provide an example of how you use this so I can include it in the readme? Just a quick cut/paste of your consuming code would be fine.

**Comment by vavanv** [comment]
using System.ComponentModel.DataAnnotations;
...

[HttpGet]
[BreadCrumb]
[Display(ResourceType = typeof (Messages), Name = "Request")]
public ActionResult RequestHeader(int headerId)
{
...
}

where Messages is resource file and "Request" is key for localized message

**Comment by martinobordin** [comment]
Could you please merge and update the nuget package with this new feature?

**Comment by thelarz** [comment]
Done, published in .62 version

**Comment by martinobordin** [comment]
Thanks :) :+1:

**Pull request merged**
